name: $(BuildID).$(Date:yyMMdd)

# CI triggers
trigger:
  batch: false
  branches:
    include:
    - release/*

# PR triggers
pr:
  autoCancel: true
  branches:
    include:
    - release/*

variables:
  # VS Code extensions run on Node.js >=10.2.0 since January 2019 (version 1.31) release
  nodeVersion: '>=10.2.0'
  npmVersion: 'latest'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build_windows
    displayName: Windows
    timeoutInMinutes: 10
    pool:
      vmImage: 'windows-2019'
      demands: npm
    steps:
      - template: templates/setup-environment.yml
      - template: templates/install-dependencies.yml
      - template: templates/compile.yml
      - script: |
          node node_modules/vscode/bin/test
        displayName: 'Run tests'

  - job: build_ubuntu
    displayName: Ubuntu
    timeoutInMinutes: 10
    pool:
      vmImage: 'ubuntu-16.04'
      demands: npm
    steps:
      - template: templates/setup-environment.yml
      - template: templates/install-dependencies.yml
      - template: templates/compile.yml
      - script: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
        displayName: 'Start xvfb'
      - script: 'node node_modules/vscode/bin/test'
        displayName: 'Run tests'
        env:
          DISPLAY: :10

  - job: build_macos
    displayName: MacOS
    timeoutInMinutes: 10
    pool:
      vmImage: 'macOS-10.14'
      demands: npm
    steps:
      - template: templates/setup-environment.yml
      - template: templates/install-dependencies.yml
      - template: templates/compile.yml
      - script: |
          node node_modules/vscode/bin/test
        displayName: 'Run tests'

- stage: publish
  displayName: Publish
  condition:
    and(
      succeeded(),
      in(variables['build.reason'], 'Manual', 'IndividualCI', 'BatchedCI')
    )
  jobs:
  - job: publish_ubuntu
    displayName: Extension
    pool:
      vmImage: 'ubuntu-16.04'
      demands: npm
    steps:
      - template: templates/setup-environment.yml
      - template: templates/install-dependencies.yml
      - template: templates/compile.yml
      - template: templates/package-artifact.yml
      - bash: |
          vsce publish -p $PUBLISHER_TOKEN
        displayName: 'Publish extension'
        env:
          PUBLISHER_TOKEN: $(build.release.token_kejxu)
        condition:
          and(
            succeeded(),
            in(variables['build.reason'], 'Manual'),
            eq(variables['build.release'], 'true')
          )
