steps:
  - bash: |
      printenv
    displayName: 'Dump environment variables'
    condition: and(succeeded(), eq(variables['system.debug'], 'true'))

  - bash: |
      echo "build.reason: $(build.reason)"
      echo "build.release: $(build.release)"
    displayName: 'Dump pipeline variables'
    condition: and(succeeded(), eq(variables['system.debug'], 'true'))

  - task: NodeTool@0
    displayName: 'Use Node version: $(nodeVersion)'
    inputs:
      versionSpec: $(nodeVersion)

  - task: Npm@1
    displayName: "Use NPM version: $(npmVersion)"
    inputs:
        command: custom
        verbose: false
        customCommand: |
          install -g npm@$(npmVersion)

  - bash: |
      echo Node Version = `node --version`
      echo NPM Version = `npm --version`
    displayName: 'Check environment versions'
    condition: and(succeeded(), eq(variables['system.debug'], 'true'))
